#!/usr/bin/env node
/**
 * Generates `dist/sw.js` after a Vite build.
 *
 * The precache list is read from the built output, so hashed asset names are
 * always correct and no manual step is needed after a deployment. The cache name
 * includes a hash of that list, which means a new build gets a new cache and old
 * caches are cleaned up on activation.
 */

import { createHash } from 'node:crypto';
import { readdir, readFile, stat, writeFile } from 'node:fs/promises';
import { join, posix, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const distDir = join(root, 'dist');
const swSourceDir = join(root, 'src', 'components', 'service-worker');

/** Files that are never precached: they are large, optional or per-request. */
const EXCLUDE = [
  /^sw\.js$/,
  /^robots\.txt$/,
  /^_headers$/,
  /^_redirects$/,
  /\.map$/,
  /^precache-manifest\.json$/,
];

/** Assets to precache beyond the essentials, kept small on purpose. */
const PRECACHE_PATTERNS = [
  /^index\.html$/,
  /^offline\.html$/,
  /^manifest\.webmanifest$/,
  /^assets\/.*\.(js|css)$/,
  /^icons\/.*\.(png|svg|ico)$/,
  /^print\/.*\.css$/,
  /^fonts\/.*\.(woff2|woff)$/,
];

async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) files.push(...(await walk(full)));
    else files.push(full);
  }
  return files;
}

function toUrlPath(absolute) {
  return relative(distDir, absolute).split(sep).join(posix.sep);
}

async function main() {
  try {
    await stat(distDir);
  } catch {
    console.error('dist/ not found — run `vite build` before building the service worker.');
    process.exit(1);
  }

  const base = process.env.VITE_BASE_PATH && process.env.VITE_BASE_PATH.length > 0
    ? process.env.VITE_BASE_PATH
    : '/';
  const basePath = base.endsWith('/') ? base : `${base}/`;

  const files = (await walk(distDir)).map(toUrlPath).sort();
  const included = files.filter(
    (file) =>
      !EXCLUDE.some((pattern) => pattern.test(file)) &&
      PRECACHE_PATTERNS.some((pattern) => pattern.test(file)),
  );

  const urls = included.map((file) => `${basePath}${file}`);
  if (!urls.includes(`${basePath}index.html`)) urls.unshift(`${basePath}index.html`);

  const hash = createHash('sha256');
  for (const file of included) {
    hash.update(file);
    hash.update(await readFile(join(distDir, file)));
  }
  const version = hash.digest('hex').slice(0, 12);

  const policy = (await readFile(join(swSourceDir, 'cache-policy.js'), 'utf8')).replace(
    /^export /gm,
    '',
  );
  const body = await readFile(join(swSourceDir, 'sw-body.js'), 'utf8');

  const header = `/*
 * Dearly service worker — generated by scripts/build-sw.mjs. Do not edit.
 * Source: src/components/service-worker/{cache-policy.js,sw-body.js}
 * Build:  ${new Date().toISOString()}
 */
const CACHE_VERSION = ${JSON.stringify(version)};
const OFFLINE_URL = ${JSON.stringify(`${basePath}offline.html`)};
const PRECACHE_URLS = ${JSON.stringify(urls, null, 2)};
`;

  const output = [header, policy, body].join('\n');
  await writeFile(join(distDir, 'sw.js'), output, 'utf8');
  await writeFile(
    join(distDir, 'precache-manifest.json'),
    `${JSON.stringify({ version, count: urls.length, urls }, null, 2)}\n`,
    'utf8',
  );

  console.log(
    `Service worker written: dist/sw.js (cache ${version}, ${urls.length} precached files).`,
  );
}

await main();
